<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookOrbit.Application\BookOrbit.Application.csproj" />
      <ProjectReference Include="..\BookOrbit.Infrastructure\BookOrbit.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Contracts\" />
      <Folder Include="Controllers\" />
      <Folder Include="Middleware\" />
    </ItemGroup>

</Project>
