<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\BookOrbit.Application\BookOrbit.Application.csproj" />
      <ProjectReference Include="..\BookOrbit.Domain\BookOrbit.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="ExternalBooks\" />
      <Folder Include="Persistence\" />
      <Folder Include="Recommendations\" />
    </ItemGroup>

</Project>
